<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc" style="margin-top: 1em;"><ul class="toc-item"><li><span><a href="#前言" data-toc-modified-id="前言-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>前言</a></span></li><li><span><a href="#创建Numpy数组" data-toc-modified-id="创建Numpy数组-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>创建Numpy数组</a></span><ul class="toc-item"><li><span><a href="#基于pythonlist的数组创建" data-toc-modified-id="基于pythonlist的数组创建-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>基于pythonlist的数组创建</a></span></li><li><span><a href="#基于numpy方法生成常用数组" data-toc-modified-id="基于numpy方法生成常用数组-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>基于numpy方法生成常用数组</a></span></li><li><span><a href="#基于numpy方法生成等间距数组" data-toc-modified-id="基于numpy方法生成等间距数组-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>基于numpy方法生成等间距数组</a></span></li><li><span><a href="#根据概率分布生成数组" data-toc-modified-id="根据概率分布生成数组-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>根据概率分布生成数组</a></span></li></ul></li><li><span><a href="#切片" data-toc-modified-id="切片-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>切片</a></span><ul class="toc-item"><li><span><a href="#python自带的list切片" data-toc-modified-id="python自带的list切片-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>python自带的list切片</a></span></li><li><span><a href="#numpy的切片" data-toc-modified-id="numpy的切片-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>numpy的切片</a></span></li></ul></li><li><span><a href="#引用" data-toc-modified-id="引用-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>引用</a></span><ul class="toc-item"><li><span><a href="#修改切片导致原序列变化" data-toc-modified-id="修改切片导致原序列变化-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>修改切片导致原序列变化</a></span></li><li><span><a href="#利用copy()函数获得备份" data-toc-modified-id="利用copy()函数获得备份-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>利用copy()函数获得备份</a></span></li></ul></li><li><span><a href="#数据的修改，转化和规整" data-toc-modified-id="数据的修改，转化和规整-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>数据的修改，转化和规整</a></span><ul class="toc-item"><li><span><a href="#对list做加减乘除操作" data-toc-modified-id="对list做加减乘除操作-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>对list做加减乘除操作</a></span></li><li><span><a href="#对numpy的数组做加减乘除操作" data-toc-modified-id="对numpy的数组做加减乘除操作-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>对numpy的数组做加减乘除操作</a></span></li><li><span><a href="#数据的转化" data-toc-modified-id="数据的转化-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>数据的转化</a></span></li><li><span><a href="#数据的规整" data-toc-modified-id="数据的规整-5.4"><span class="toc-item-num">5.4&nbsp;&nbsp;</span>数据的规整</a></span></li></ul></li><li><span><a href="#Mask" data-toc-modified-id="Mask-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Mask</a></span></li><li><span><a href="#通用序列函数" data-toc-modified-id="通用序列函数-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>通用序列函数</a></span><ul class="toc-item"><li><span><a href="#all和any" data-toc-modified-id="all和any-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>all和any</a></span></li><li><span><a href="#maximum和minimum" data-toc-modified-id="maximum和minimum-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>maximum和minimum</a></span></li><li><span><a href="#unique" data-toc-modified-id="unique-7.3"><span class="toc-item-num">7.3&nbsp;&nbsp;</span>unique</a></span></li><li><span><a href="#diff" data-toc-modified-id="diff-7.4"><span class="toc-item-num">7.4&nbsp;&nbsp;</span>diff</a></span></li><li><span><a href="#三目表达式" data-toc-modified-id="三目表达式-7.5"><span class="toc-item-num">7.5&nbsp;&nbsp;</span>三目表达式</a></span></li></ul></li><li><span><a href="#统计函数" data-toc-modified-id="统计函数-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>统计函数</a></span><ul class="toc-item"><li><span><a href="#最大最小值" data-toc-modified-id="最大最小值-8.1"><span class="toc-item-num">8.1&nbsp;&nbsp;</span>最大最小值</a></span></li><li><span><a href="#均值，方差和标准差" data-toc-modified-id="均值，方差和标准差-8.2"><span class="toc-item-num">8.2&nbsp;&nbsp;</span>均值，方差和标准差</a></span></li></ul></li></ul></div>

# 前言
numpy是一个十分强大的python库，相比于python自带的list，numpy它能够支持更多更加灵活的操作。

在本文中仅仅介绍在《量化交易之路》中使用过的numpy，其他内容还请查阅：
http://old.sebug.net/paper/books/scipydoc/numpy_intro.html

# 创建Numpy数组
numpy最重要的就是数组了。相比于python中的list，numpy中的数组数据类型提供了更为灵活丰富的操作。
下面，演示几种一般的numpy数组创建方式。

## 基于pythonlist的数组创建
这种方式创建数组比较利于我们从python的list过度到numpy的数组。

注意，会发现numpy数组元素之间不是用逗号，而是用空格隔开的。

** 导入numpy模块：**

In [4]:
import numpy as np

**基于python的list创建numpy数组**

In [6]:
a=[1,2,3,4]
print(a)
print(type(a))

[1, 2, 3, 4]
<class 'list'>


In [5]:
b=np.array(a)
print(b)
print(type(b))

[1 2 3 4]
<class 'numpy.ndarray'>


** 复杂的list也可以生成相同结构的数组**

In [8]:
c=[[1,2,3],[4,5,6]]
print(c)
print(type(c))
d=np.array(c)
print(d)
print(type(d))
# zeros，ones，empty，eye，ones_like,zeros_like

[[1, 2, 3], [4, 5, 6]]
<class 'list'>
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


## 基于numpy方法生成常用数组
一般而言，我们会有numpy数组去表示矩阵，然后用矩阵的相关运算来进行后续的操作。
而在矩阵的运算中，单位矩阵，是一个很重要的矩阵。对于一个4*4的单位矩阵，如果需要我们通过先构建list，再生成数组的形式来操作的话，显得太过麻烦了。
因此，numpy就提供共了很多简单的方法生成一些常用的矩阵。

** 根据输入的矩阵大小生成全零矩阵**

In [12]:
# 仅传入一个数组，表示生成一个长度为n的一维数组
np_zero=np.zeros(5)
print(np_zero)
# 以list的方式传入所需要的全零矩阵的行与列数目
np_zero=np.zeros([3,4])
print(np_zero)

[ 0.  0.  0.  0.  0.]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


**根据输入的矩阵大小生成全一矩阵**

In [11]:
np_ones=np.ones([2,3])
print(np_ones)

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


**模仿输入的矩阵，生成一个相同size的全零或者全一矩阵**

In [13]:
# 输入矩阵大小是2*3
a=[[1,2,3],[4,5,6]]
np_zeros=np.zeros_like(a)
np_ones=np.ones_like(a)
print(np_zeros)
print(np_ones)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]


**生成单位矩阵**

In [14]:
# 单位矩阵由于其特殊的形式，我们只需要告诉numpy需要几阶的单位阵就好。
np_eyes=np.eye(5)
print(np_eyes)

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


## 基于numpy方法生成等间距数组
有的时候，我们可能会需要在最大值和最小值之间，平均的生成k个点(包括最大最小值点）
而numpy也提供了类似的方法给我们

In [21]:
# 等间距的生成np.array
# 计算公式是linspace(a,b,c),
# 数组的开头是a，结尾是b，c表示这个数组中要有几个点
#（其实就是把a~b这段距离平均分为c-1份）
np_linespace=np.linspace(0,10,11)
print(np_linespace)

[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]


## 根据概率分布生成数组
这里这么想，我有一个数组，里面有n个元素。我们把这n个元素看做是一个随机变量，并且都属于同一个分布。
那么，接下来我的目标就是基于这个分布，生成n个属于这个分布的元素。

示例中用一种基本的分布，标准正态分布，来进行演示。

In [26]:
# 生成一个长度为10的正态分布list
np_normal_list=np.random.standard_normal(10)
print(np_normal_list)
# 生成一个size位3*3的正态分布数组,最好传入tuple，当然list也没问题
np_normal_met=np.random.standard_normal([3,3])
print(np_normal_met)

[ 1.17573962  0.28994448  2.02210781 -0.19290488 -2.07559477  0.02969273
  0.98586402 -0.08547048 -0.36726295 -1.56878403]
[[-0.03599318 -0.23291393  2.03278574]
 [-0.86697868 -0.22205171 -0.01466563]
 [-0.99376621 -0.895311   -0.42112069]]


# 切片
切片是python的一大亮点，那么numpy中当然也提供了相关操作，甚至是更加便捷的切片操作。
下面，我们从python的切片开始，来看看numpy中的切片。

## python自带的list切片

In [27]:
a=[[1,2,3],[4,5,6],[7,8,9]]
print(a)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


**获得第二行**

In [28]:
a_r_2=a[1]
print(a_r_2)

[4, 5, 6]


In [29]:
a_r_2_2=a[1][:]
print(a_r_2_2)

[4, 5, 6]


**获得第二列**

In [46]:
a_c_2=[col[1] for col in a]
print(a_c_2)

[2, 5, 8]


** 获得第i行j列个元素**

In [47]:
a_i_j=a[1][2]
print(a_i_j)

6


## numpy的切片
从上面我们发现，其他还好，但是要获得矩阵某一列的元素时，我们还是需要借助类似于for循环的方式实现。
而numpy可以有更加方便的方式。

In [48]:
np_a=np.array(a)
print(np_a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**获得第二行**

In [49]:
np_r2=np_a[1]
print(np_r2)

[4 5 6]


In [50]:
np_r2_2=np_a[1,:]
print(np_r2_2)

[4 5 6]


**获得第二列**

In [52]:
np_c2=np_a[:,1]
print(np_c2)

[2 5 8]


**获得第i行j列个元素**

In [53]:
np_i_j=np_a[2,1]
print(np_i_j)

8


# 引用
关于numpy的数组，当我们利用切片获得一个子序列时，我们其实获得的是原序列的一个引用，这个引用指向原序列的一部分。
那么，当我们在子序列上修改时，原序列也会跟着变化

## 修改切片导致原序列变化

In [54]:
# 获得原序列
eyes=np.eye(3)
print(eyes)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [56]:
# 得到第二列，并修改第一个元素为2
col2=eyes[:,1]
col2[0]=2
print(col2)

[ 2.  1.  0.]


In [58]:
# 查看原序列
print(eyes)

[[ 1.  2.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## 利用copy()函数获得备份
为了防止原序列被修改，可以使用copy函数，获得一个原序列的真实备份，那么对于切片的操作，就不会影响原序列了。

In [59]:
eyes=np.eye(3)
print(eyes)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [61]:
cols=eyes[:,1].copy()
cols[0]=2
print(cols)

[ 2.  1.  0.]


In [62]:
print(eyes)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


# 数据的修改，转化和规整
在python中，对于list做加减乘除，是会被认为是对list这个整体进行操作。

而在numpy中，每一个对numpy数组的操作，都被认为是对数组中每一个元素的操作

## 对list做加减乘除操作

In [63]:
a=[[1,2],[3,4]]
print(a*3)

[[1, 2], [3, 4], [1, 2], [3, 4], [1, 2], [3, 4]]


## 对numpy的数组做加减乘除操作

In [66]:
np_a=np.array(a)
print(np_a)

[[1 2]
 [3 4]]


In [67]:
print(np_a*2)

[[2 4]
 [6 8]]


In [68]:
print(np_a+3)

[[4 5]
 [6 7]]


In [70]:
np_b=np.eye(2)
print(np_b)

[[ 1.  0.]
 [ 0.  1.]]


In [71]:
print(np_a+np_b)

[[ 2.  2.]
 [ 3.  5.]]


## 数据的转化
当我们需要把元素为float类型的矩阵转化为int，或者将元素为int的矩阵转化为float，可以使用np数组自带的astype函数

In [76]:
np_float=np.array([[3.1415,2.7856],[9.23475,5.7429]])
print(np_float)

[[ 3.1415   2.7856 ]
 [ 9.23475  5.7429 ]]


In [78]:
np_float=np_float.astype(int)
print(np_float)

[[3 2]
 [9 5]]


In [79]:
np_float=np_float.astype(float)
print(np_float)

[[ 3.  2.]
 [ 9.  5.]]


## 数据的规整
当我们对数据的精度有要求时，可以用numpy库提供的方法，对数据进行floor，ceil，round等操作

In [80]:
np_float=np.array([[3.1415,2.7856],[9.23475,5.7429]])
print(np_float)

[[ 3.1415   2.7856 ]
 [ 9.23475  5.7429 ]]


In [81]:
np_round=np.round(np_float,2)
print(np_round)

[[ 3.14  2.79]
 [ 9.23  5.74]]


# Mask
mask是numpy中的每一个元素做了条件运算之后得到的结果，通过该结果，我们可以筛选出我们需要的元素。

** 得到mask**

In [83]:
np_int=np.array([[1,2,3],[4,5,6]])
np_mask=np_int%2==0
print(np_mask)

[[False  True False]
 [ True False  True]]
[[1 2 3]
 [4 5 6]]


** 利用mask来筛选元素**

In [84]:
np_int_mask=np_int[np_mask]
print(np_int_mask)

[2 4 6]


# 通用序列函数
通用序列函数，可以看做是numpy帮我们把一些常用的全局mask给封装起来。比如判断是否所有元素都大于零，是否有元素小于零等等。

## all和any
all表示全部符合，比如是否全部都大于零
any表示存在符合，比如是否存在大于零

**all，判断是否元素都大于0**

In [85]:
np_test=np.array([[1,2,3],[4,5,6]])
print(np.all(np_test>0))

True


**any,判断是否有元素小于零**

In [86]:
np_test=np.array([[-1,2,3],[4,5,6]])
print(np.any(np_test<0))

True


## maximum和minimum
这两个函数用来比较两个数组中的元素，并留下较大，或者较小那个。

** maximum，比较两个数组，留下每个位置上较大的那个**

In [87]:
np_1=np.array([2,4,6])
np_2=np.array([1,5,3])
print(np.maximum(np_1,np_2))

[2 5 6]


** minimum,比较两个数组，留下每个位置上较小的那个**

In [88]:
print(np.minimum(np_1,np_2))

[1 4 3]


## unique
对于用重复元素的数组，删除重复元素，只留下一个元素,并返回一个一维数组

In [89]:
np_a=np.array([[1,2,3],[2,4,5]])
print(np.unique(np_a))

[1 2 3 4 5]


## diff
判断同一个array中某一个维度上不同。
对于axis=1，表示判断第二列和第一列的差，第三列和第二列的差....
对于axis=2，表示判断第二行和第一行的差，第三行和第二行的差....

In [94]:
np_a=np.array([[1,2,3],[2,4,5]])
print(np.diff(np_a,axis=1))
print(np.diff(np_a,axis=0))

[[1 1]
 [2 1]]
[[1 2 2]]


## 三目表达式
在numpy中，还提供一种叫做三目表达式的操作，
对于numpy数组中，如果元素符合条件，那么执行动作A，否则执行动作B。

** 数组元素为偶数，设置为0，否则设置为1**

In [95]:
np_a=np.array([[1,2,3],[4,5,6]])
print(np.where(np_a%2==0,0,1))

[[1 0 1]
 [0 1 0]]


** 数组元素为偶数，设置为0，否则不变**

In [97]:
print(np.where(np_a%2==0,0,np_a))

[[1 0 3]
 [0 5 0]]


** 数组元素为偶数，且大于等于4，设置为0，否则不变**

In [98]:
print(np.where(np.logical_and(np_a%2==0,np_a>=4),0,np_a))

[[1 2 3]
 [0 5 0]]


# 统计函数
numpy同样提供了一些统计函数，可以帮助计算均值，方差，标准差，最大值，最小值等统计量

In [99]:
np_a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np_a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 最大最小值
numpy提供的函数可以统计全局的极值，也可以提供每行或者每列的最大最小值

** 全局最大值**

In [100]:
print(np.max(np_a))

9


**每行的最大值**

In [101]:
print(np.max(np_a,axis=1))

[3 6 9]


**每列最大值**

In [102]:
print(np.max(np_a,axis=0))

[7 8 9]


## 均值，方差和标准差
均值，方差和标准差的全局用法和上面一样，

但按列和按行取，就刚好相反，

下面就仅演示按列取均值，方差和标准差。

** 每一列的均值**

In [106]:
print(np.mean(np_a.astype(float),axis=0))

[ 4.  5.  6.]


**每一列的方差**

In [109]:
print(np.var(np_a,axis=0))

[ 6.  6.  6.]


** 每一列的标准差**

In [110]:
print(np.std(np_a,axis=0))

[ 2.44948974  2.44948974  2.44948974]
